version: '3.8'

services:
  aireclame-app:
    build: .
    container_name: aireclame-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/data/ads/ads_database.db
      - CUDA_VISIBLE_DEVICES=0,1,2,3  # Ajustează pentru numărul de GPU-uri
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./config:/app/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - aireclame-network

  aireclame-crawler:
    build: .
    container_name: aireclame-crawler
    command: python3 scripts/improved_crawler.py
    environment:
      - CUDA_VISIBLE_DEVICES=0,1,2,3
      - DATABASE_PATH=/data/ads/ads_database.db
      - PYTHONPATH=/app
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./api_keys.json:/app/api_keys.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      - aireclame-app
    networks:
      - aireclame-network

  nginx:
    image: nginx:alpine
    container_name: aireclame-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - aireclame-app
    restart: unless-stopped
    networks:
      - aireclame-network

networks:
  aireclame-network:
    driver: bridge

volumes:
  aireclame-data:
    driver: local
